apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kabal-file-api
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "300M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{ image }}
  azure:
    application:
      enabled: true
      allowAllUsers: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  port: 7080
  accessPolicy:
    inbound:
      rules:
        - application: kabal-api
        - application: kabal-document
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  secureLogs:
    enabled: true
  webproxy: true
  gcp:
    buckets:
    {{#each buckets}}
       - name: {{this}}
    {{/each}}
  env:
    {{#each envs}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}
